spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/family_jira
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/init.sql
      data-locations: classpath*:sql/data.sql


